### ISSUE TITLE
next version provide quality flag for toi data to reflect samples identified in QA steps (toi_bottle_check.csv)

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-eims-toi-ncp-gop#7]

**Comment by katemorkeski** [comment]
Currently the identified samples are excluded completely

**Comment by katemorkeski** [comment]
Updated to provide quality flag for new toi v3 data and to retain all rows of new data in product data table. Previous version are provided with iode quality flag = 1.

**Comment by katemorkeski** [comment]
Removed flagging in product data table for v 6.3 because fixed the issues
